# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MColName',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('col_index', models.PositiveIntegerField()),
                ('col_name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='MInfo',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('f01', models.CharField(default=b'', max_length=256)),
                ('f02', models.CharField(default=b'', max_length=256)),
                ('f03', models.CharField(default=b'', max_length=256)),
                ('f04', models.CharField(default=b'', max_length=256)),
                ('f05', models.CharField(default=b'', max_length=256)),
                ('f06', models.CharField(default=b'', max_length=256)),
                ('f07', models.CharField(default=b'', max_length=256)),
                ('f08', models.CharField(default=b'', max_length=256)),
                ('f09', models.CharField(default=b'', max_length=256)),
                ('f10', models.CharField(default=b'', max_length=256)),
                ('f11', models.CharField(default=b'', max_length=256)),
                ('f12', models.CharField(default=b'', max_length=256)),
                ('f13', models.CharField(default=b'', max_length=256)),
                ('f14', models.CharField(default=b'', max_length=256)),
                ('f15', models.CharField(default=b'', max_length=256)),
                ('f16', models.CharField(default=b'', max_length=256)),
                ('f17', models.CharField(default=b'', max_length=256)),
                ('f18', models.CharField(default=b'', max_length=256)),
                ('f19', models.CharField(default=b'', max_length=256)),
                ('f20', models.CharField(default=b'', max_length=256)),
                ('f21', models.CharField(default=b'', max_length=256)),
                ('f22', models.CharField(default=b'', max_length=256)),
                ('f23', models.CharField(default=b'', max_length=256)),
                ('f24', models.CharField(default=b'', max_length=256)),
                ('f25', models.CharField(default=b'', max_length=256)),
                ('f26', models.CharField(default=b'', max_length=256)),
                ('f27', models.CharField(default=b'', max_length=256)),
                ('f28', models.CharField(default=b'', max_length=256)),
                ('f29', models.CharField(default=b'', max_length=256)),
                ('f30', models.CharField(default=b'', max_length=256)),
                ('f31', models.CharField(default=b'', max_length=256)),
                ('f32', models.CharField(default=b'', max_length=256)),
                ('f33', models.CharField(default=b'', max_length=256)),
                ('f34', models.CharField(default=b'', max_length=256)),
                ('f35', models.CharField(default=b'', max_length=256)),
                ('f36', models.CharField(default=b'', max_length=256)),
                ('f37', models.CharField(default=b'', max_length=256)),
                ('f38', models.CharField(default=b'', max_length=256)),
                ('f39', models.CharField(default=b'', max_length=256)),
                ('f40', models.CharField(default=b'', max_length=256)),
                ('f41', models.CharField(default=b'', max_length=256)),
                ('f42', models.CharField(default=b'', max_length=256)),
                ('f43', models.CharField(default=b'', max_length=256)),
                ('f44', models.CharField(default=b'', max_length=256)),
                ('f45', models.CharField(default=b'', max_length=256)),
                ('f46', models.CharField(default=b'', max_length=256)),
                ('f47', models.CharField(default=b'', max_length=256)),
                ('f48', models.CharField(default=b'', max_length=256)),
                ('f49', models.CharField(default=b'', max_length=256)),
                ('f50', models.CharField(default=b'', max_length=256)),
                ('f51', models.CharField(default=b'', max_length=256)),
                ('f52', models.CharField(default=b'', max_length=256)),
                ('f53', models.CharField(default=b'', max_length=256)),
                ('f54', models.CharField(default=b'', max_length=256)),
                ('f55', models.CharField(default=b'', max_length=256)),
                ('f56', models.CharField(default=b'', max_length=256)),
                ('f57', models.CharField(default=b'', max_length=256)),
                ('f58', models.CharField(default=b'', max_length=256)),
                ('f59', models.CharField(default=b'', max_length=256)),
                ('f60', models.CharField(default=b'', max_length=256)),
                ('f61', models.CharField(default=b'', max_length=256)),
                ('f62', models.CharField(default=b'', max_length=256)),
                ('f63', models.CharField(default=b'', max_length=256)),
                ('f64', models.CharField(default=b'', max_length=256)),
                ('f65', models.CharField(default=b'', max_length=256)),
                ('f66', models.CharField(default=b'', max_length=256)),
                ('f67', models.CharField(default=b'', max_length=256)),
                ('f68', models.CharField(default=b'', max_length=256)),
                ('f69', models.CharField(default=b'', max_length=256)),
                ('f70', models.CharField(default=b'', max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='MUser',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('name', models.CharField(max_length=32)),
                ('passwd', models.CharField(max_length=32)),
            ],
        ),
    ]
