{
    "button": [
        {
            "name": "下午茶",
            "sub_button": [
                {
                    "type": "view",
                    "name": "查看记录",
                    "url": "http://gohome123.pw/expense/"
                },
                {
                    "type": "view",
                    "name": "添加记录",
                    "url": "https://www.gohome123.cn/expense/"
                },
                {
                    "type": "click",
                    "name": "导出邮件",
                    "key": "V1001_GOOD"
                }
            ]
        },
        {
            "name": "其他",
            "sub_button": [
                {
                    "type": "click",
                    "name": "未实现",
                    "key": "V1001_GOOD"
                }
            ]
        },
        {
            "name": "关于",
            "sub_button": [
                {
                    "type": "click",
                    "name": "未实现",
                    "key": "V1001_GOOD"
                }
            ]
        }
    ]
}
